---
title: 'Generate manuscript artefacts'
author: 'Jay Achar'
date: '`r Sys.time()`'
output:
  html_document:
    code_folding: hide
    toc: true
    toc_depth: 2
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(forecast)
suppressMessages(library(tidyverse))
library(patchwork)
library(flextable)
library(officer)
absspace <- function(x, ...) {
  format(abs(x), ..., big.mark = " ",
         scientific = FALSE,
         trim = TRUE)
}

```

```{r source-data-functions, message=FALSE}
files <- list.files(here("R"))
walk(files,
     ~source(here("R", .x)))
# returns a list of constants
const <- constants()

raw <- suppressWarnings(read_data("notifications"))
dd <- prepare_data(raw, const = const)
clean <- prepare_long_data(dd)

preds <- readRDS(here::here("artefacts/manuscript_predictions.rds"))

```

## Figures {.tabset .tabset-pills }

### Main figure 1

```{r main-figure-1 }
# create ts_df list
ts_list <- clean$region %>%
        group_by(location, year, age_group) %>%
        summarise(cases = sum(cases),
                  .groups = "drop") %>%
        group_by(age_group) %>%
        group_split()

forecast_list <- preds$age_region %>%
        select(-sd, region = location) %>%
        mutate(year = 2020) %>%
        group_by(age_group) %>%
        group_split()

ribbon_df <- map2(ts_list,
                  forecast_list,
     function(ts, forecast) {
       ts %>%
        filter(year == 2019) %>%
        mutate(lower95 = cases,
               upper95 = cases) %>%
        select(age_group,
               region = location,
               point = cases,
               lower95, upper95,
               year) %>%
        bind_rows(forecast)
     })

age_group_labels <- c("0-4 years",
                      "5-14 years",
                      "15+ years")

arima_plots <- pmap(list(ts_list,
     forecast_list,
     ribbon_df,
     age_group_labels),
     function(ts, forecast, ribbon, age_label) {
       ggplot(ts,
              aes(x = year)) +
         geom_line(aes(y = cases,
                       color = location)) +
         geom_point(aes(y = cases,
                        color = location),
                    size = 1) +
         geom_ribbon(
           data = ribbon,
           mapping = aes(
             ymin = lower95,
             ymax = upper95,
             group = region,
             fill = region
           ),
           alpha = 0.3
         ) +
         scale_color_discrete(guide = "none") +
         scale_fill_discrete(guide = "none") +
         scale_y_sqrt(label = absspace) +
         labs(x = "Year",
              y = "Cases (sqrt transformed)",
              fill = "WHO Region",
              title = age_label) +
         theme_minimal()

     }) %>%
  wrap_plots(ncol = 3) +
  scale_fill_discrete()

ggsave(here::here("figures/main/main_arima_plots.png"),
       arima_plots,
       width = 15,
       height = 8)

ggsave(here::here("figures/main/main_arima_plots.eps"),
       arima_plots,
       width = 15,
       height = 8)

arima_plots
```

### Main table 1

```{r main-table-1}

mt1_data <- clean$global %>%
  select(-location) %>%
  mutate(sex = factor(sex,
                      levels = c("m", "f", "All"),
                      labels = c("Male", "Female", "All"),
                      ordered = TRUE)) %>%
  group_by(age_group) %>%
  group_split() %>%
  map(function(x) {
  wide <- pivot_wider(
    x,
    id_cols = year,
    names_from = sex,
    values_from = cases
  ) %>%
          select(year, Male, Female)

  wide$abs_diff <- wide[[grep("Male", names(wide))]] - wide[[grep("Female", names(wide))]]
  wide$ratio <- round(wide[[grep("Male", names(wide))]] / wide[[grep("Female", names(wide))]],
                       3)
  wide
  }) %>%
  purrr::reduce(left_join, by = "year")

mt1 <- flextable(mt1_data) %>%
  set_header_labels(
    year = "Year",
    "year",
    Female.x = "Female",
    Male.x = "Male",
    abs_diff.x = "Difference (n)",
    ratio.x = "M:F ratio",
    Female.y = "Female",
    Male.y = "Male",
    abs_diff.y = "Difference (n)",
    ratio.y = "M:F ratio",
    Female = "Female",
    Male = "Male",
    abs_diff = "Difference (n)",
    ratio = "M:F ratio"
  ) %>%
  add_header_row(
    values = c("", "0-4 years",
               "5-14 years",
               "15+ years"),
    colwidths = c(1, 4, 4, 4)
  ) %>%
  set_table_properties(layout = "autofit", width = 1) %>%
  fontsize(size = 9, part = "all") %>%
  theme_box()
mt1
```

### Main table 2

```{r main-table-2}
mt2_all_regions <- clean$global %>%
  filter(year == 2019) %>%
  group_by(age_group, sex) %>%
  mutate(sex = ifelse(sex == "m", "Male", "Female")) %>%
  summarise(cases = sum(cases),
            location = "All",
            .groups = "drop") %>%
  select(location, sex, age_group, cases)


mt2_data <- clean$region %>%
  filter(year == 2019) %>%
  group_by(location, sex, age_group) %>%
  summarise(cases = sum(cases),
            .groups = "drop") %>%
  mutate(sex = factor(sex,
                      levels = c("m", "f", "All"),
                      labels = c("Male", "Female", "All"),
                      ordered = TRUE)) %>%
  bind_rows(mt2_all_regions) %>%
  pivot_wider(names_from = "sex", values_from = cases) %>%
  mutate(abs_diff = Male - Female,
         ratio = round(Male / Female, 3)) %>%
  mutate(location = factor(location,
                           levels = c(const$who_regions, "All"),
                           ordered = TRUE)) %>%
  arrange(age_group, location)


mt2 <- flextable(mt2_data,
                 col_keys = c("age_group", "location", "Male",
                              "Female", "abs_diff", "ratio")) %>%
  set_header_labels(
    age_group = "",
    location = "Region",
    abs_diff = "Difference (N)",
    ratio = "M:F ratio"
  ) %>%
  set_table_properties(layout = "autofit", width = 1) %>%
  merge_v(j = ~ age_group) %>%
  fontsize(size = 9, part = "all") %>%
  theme_box()

mt2
```

### Supplement figure 1

```{r supp-figure-1, fig.height = 15, fig.width= 10}
age_region_plots <- clean$region %>%
  bind_rows(clean$global) %>%
  group_by(location) %>%
  nest() %>%
  mutate(plots = map2(data, location,
                      function(region, name) {
    ggplot(data = region,
           aes(
             x = year,
             y = cases / 1000,
             group = sex,
             color = sex
           )) +
      geom_line() +
      scale_color_discrete(guide = "none") +
      facet_wrap(. ~ age_group, scales = "free_y") +
      theme_minimal() +
      labs(x = "",
           y = "Cases (thousands)",
           title = name) +
      theme(strip.background = element_blank(),
            strip.text = element_text())

  }))


aggregate_plot <- wrap_plots(age_region_plots$plots, nrow = 7) +
  plot_annotation(title = "Notifications between 2014 and 2020 by age group and WHO Region",
                  caption = "Source: WHO Global TB Programme") +
  scale_color_discrete() +
  theme(legend.position = "bottom")

ggsave(here::here("figures/supplement/supplement1_age_sex_region_notifcations.png"),
       plot = aggregate_plot,
       width = 10,
       height = 15)

aggregate_plot
```

### Supplement figure 4

```{r supp-fig-4}

diff_data <- clean$region %>%
        group_by(location, age_group, year) %>%
        summarise(cases = sum(cases),
                  .groups = "drop") %>%
        group_by(location, age_group) %>%
        mutate(diff = cases - lag(cases),
               percent = round(cases / lag(cases) * 100, 1)) %>%
        filter(!is.na(diff))

global_diff_data <- clean$region %>%
        group_by(age_group, year) %>%
        summarise(cases = sum(cases),
                  .groups = "drop") %>%
        group_by(age_group) %>%
        mutate(diff = cases - lag(cases),
               percent = round(cases / lag(cases) * 100, 1)) %>%
        filter(!is.na(diff))

diff_plot <- ggplot(diff_data,
                    aes(x = year,
                        y = percent)) +
        geom_line(aes(group = location,
                      color = location), alpha = 0.2) +
        geom_point(data = global_diff_data, color = "red") +
        geom_line(data = global_diff_data,
                  color = "red",
                  alpha = 0.5) +
        geom_hline(yintercept = 100, alpha = 0.6) +
        theme_minimal() +
        coord_cartesian(ylim = c(50, 150)) +
        facet_grid(age_group ~ .) +

        labs(y = "Percent change on previous year",
             x = "Year",
             color = "WHO Region")

ggsave(here::here("figures/supplement/supplement4_age_region_annual_change.png"),
       plot = diff_plot)

diff_plot

```

### Supplement table 1

```{r supp_table-1}

base <- clean$region %>%
  filter(year >= 2019) %>%
  group_by(age_group, sex, year) %>%
  summarise(cases = sum(cases),
            .groups = "drop")

st1_data <- clean$region %>%
  filter(year >= 2019) %>%
  group_by(age_group, year) %>%
  summarise(cases = sum(cases),
            .groups = "drop") %>%
  mutate(sex = "All") %>%
  bind_rows(base) %>%
  pivot_wider(names_from = "year",
              names_prefix = "y_",
              values_from = cases) %>%
   mutate(abs_diff = y_2020 - y_2019,
         perc = round((y_2020 - y_2019) / y_2019 * 100, 2)) %>%
  mutate(sex = factor(sex,
                      levels = c("m", "f", "All"),
                      labels = c("Male", "Female", "All"),
                      ordered = TRUE)) %>%
  arrange(age_group, sex)

st1 <- flextable(st1_data,
                 col_keys = c("age_group", "sex", "y_2019",
                              "y_2020", "abs_diff", "perc")) %>%
  set_header_labels(
    age_group = "",
    sex = "Sex",
    y_2019 = "Observed 2019",
    y_2020 = "Observed 2020",
    abs_diff = "Difference (N)",
    perc = "Percent difference (%)"
  ) %>%
  set_table_properties(layout = "autofit", width = 1) %>%
  merge_v(j = ~ age_group) %>%
  fontsize(size = 9, part = "all") %>%
  theme_box()

st1
```

### Supplement table 2

```{r supp-table-2}

st2_all_regions <- clean$global %>%
  filter(year %in% c(2019, 2020)) %>%
  group_by(age_group, year) %>%
  summarise(cases = sum(cases),
            location = "All",
            .groups = "drop") %>%
  select(location, year, age_group, cases)

st2_data <- clean$region %>%
  filter(year >= 2019) %>%
  group_by(location, year, age_group) %>%
  summarise(cases = sum(cases),
            .groups = "drop") %>%
  bind_rows(st2_all_regions) %>%
  pivot_wider(names_from = "year", values_from = cases,
              names_prefix = "y_" ) %>%
  mutate(abs_diff = y_2020 - y_2019,
         perc = round((y_2020 - y_2019) / y_2019 * 100, 2)) %>%
  mutate(location = factor(location,
                           levels = c(const$who_regions, "All"),
                           ordered = TRUE)) %>%
  arrange(age_group, location)


st2 <- flextable(st2_data,
                 col_keys = c("age_group", "location", "y_2019",
                              "y_2020", "abs_diff", "perc")) %>%
  set_header_labels(
    age_group = "",
    location = "Region",
    y_2019 = "Observed 2019",
    y_2020 = "Observed 2020",
    abs_diff = "Difference (N)",
    perc = "Percent difference (%)"
  ) %>%
  set_table_properties(layout = "autofit", width = 1) %>%
  merge_v(j = ~ age_group) %>%
  fontsize(size = 9, part = "all") %>%
  theme_box()

st2
```

### Supplement table 3

```{r supp-table-3}
age_group_totals <- clean$global %>%
        filter(year == 2020) %>%
        group_by(age_group) %>%
        summarise(actual = sum(cases),
                  .groups = "drop") %>%
        mutate(sex = "all") %>%
        select(sex, age_group, actual)


st3_data <- clean$global %>%
        filter(year == 2020) %>%
        select(-location, -year, actual = cases) %>%
        bind_rows(age_group_totals) %>%
        arrange(age_group, sex) %>%
        left_join(preds$age_sex %>% select(-sd, predicted = point),
                  by = c("age_group", "sex")) %>%
        mutate(sex = factor(sex, levels = c("m", "f", "all"),
                            labels = c("Male", "Female", "All"),
                            ordered = TRUE),
               predicted_text = glue::glue("{predicted} [{as.integer(lower95)} - {as.integer(upper95)}]")) %>%
        mutate(percent_text = glue::glue("{round((actual - predicted) / predicted * 100, 1)} [{round((actual - lower95) / lower95 * 100, 1)} - {round((actual - upper95) / upper95 * 100, 1)}]")) %>%
        mutate(diff_text = glue::glue("{actual - predicted} [{actual - as.integer(lower95)} - {actual - as.integer(upper95)}]")) %>%
  arrange(age_group, sex)

st3 <- flextable(st3_data,
                col_keys = c("age_group", "sex", "actual", "predicted_text",
                             "diff_text", "percent_text")) %>%
        set_header_labels(sex = "Sex", age_group = "", actual = "Actual notifications",
                          predicted_text = "Predicted notifications (N, [95% CI])",
                          diff_text = "Difference (N, [95% CI])", percent_text = "% [95% CI]") %>%
        set_table_properties(layout = "autofit", width = 1) %>%
        merge_v(j = ~ age_group) %>%
        fontsize(size = 9, part = "all") %>%
        theme_box()

st3
```

### Supplement table 4

```{r supp-table-4}
age_group_totals <- clean$global %>%
        filter(year == 2020) %>%
        group_by(age_group) %>%
        summarise(actual = sum(cases),
                  .groups = "drop") %>%
        mutate(location = "All") %>%
        select(location, age_group, actual)

predictions_df <-
  bind_rows(preds$age %>% mutate(location = "All"), preds$age_region) %>%
  select(-sd, predicted = point)


st4_data <- clean$region %>%
        filter(year == 2020) %>%
  group_by(location, age_group) %>%
  summarise(cases = sum(cases),
            .groups = "drop") %>%
        rename(actual = cases) %>%
        bind_rows(age_group_totals) %>%
        arrange(age_group, location) %>%
        left_join(predictions_df,
                  by = c("age_group", "location")) %>%
        mutate(predicted_text = glue::glue("{predicted} [{as.integer(lower95)} - {as.integer(upper95)}]")) %>%
        mutate(percent_text = glue::glue("{round((actual - predicted) / predicted * 100, 1)} [{round((actual - lower95) / lower95 * 100, 1)} - {round((actual - upper95) / upper95 * 100, 1)}]")) %>%
        mutate(diff_text = glue::glue("{actual - predicted} [{actual - as.integer(lower95)} - {actual - as.integer(upper95)}]")) %>%
  mutate(location = factor(location,
                           levels = c(const$who_regions, "All"),
                           ordered = TRUE)) %>%
  arrange(age_group, location)

st4 <- flextable(st4_data,
                col_keys = c("age_group", "location", "actual", "predicted_text",
                             "diff_text", "percent_text")) %>%
        set_header_labels(location = "WHO Region", age_group = "", actual = "Actual notifications",
                          predicted_text = "Predicted notifications (N, [95% CI])",
                          diff_text = "Difference (N, [95% CI])", percent_text = "% [95% CI]") %>%
        set_table_properties(layout = "autofit", width = 1) %>%
        merge_v(j = ~ age_group) %>%
        fontsize(size = 9, part = "all") %>%
        theme_box()

st4
```

```{r save-tables}

ps_landscape <- prop_section(page_size = page_size(orient = "landscape"))
ps_portrait <- prop_section(page_size = page_size(orient = "portrait"))

tables_doc <- read_docx() %>%
  body_add_par("Main Table 1", style = "heading 1") %>%
  body_add_flextable(value = mt1) %>%
  body_add_break() %>%
  body_add_par("Main Table 2", style = "heading 1") %>%
  body_add_flextable(value = mt2) %>%
  body_add_break() %>%
  body_add_par("Supplement Table 1", style = "heading 1") %>%
  body_add_flextable(value = st1) %>%
  body_add_break() %>%
  body_add_par("Supplement Table 2", style = "heading 1") %>%
  body_add_flextable(value = st2) %>%
  body_end_block_section(value = block_section(property = ps_portrait)) %>%
  body_add_par("Supplement Table 3", style = "heading 1") %>%
  body_add_flextable(value = st3) %>%
  body_end_block_section(value = block_section(property = ps_landscape)) %>%
  body_add_par("Supplement Table 4", style = "heading 1") %>%
  body_add_flextable(value = st4) %>%
  body_end_block_section(value = block_section(property = ps_landscape))

print(tables_doc, target = here::here("figures/tables.docx"))

```
