---
title: "Generate prediction data"
author: 'Jay Achar'
date: "`r Sys.time()`"
output:
  html_document:
    code_folding: hide
    toc: true
    toc_depth: 2
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

suppressMessages(library(tidyverse))
library(here)
library(forecast)
```

```{r source-functions}
files <- list.files(here("R"))
walk(files,
     ~source(here("R", .x)))
```

```{r read-in-data, message=FALSE, warning=FALSE}
raw <- read_data("notifications")
```

```{r define-constants-functions}
# returns a list of constants
const <- constants()
```

```{r create-predicted-data }
dd <- prepare_data(raw, const = const)
# create training data
## remove 2020
regions <- dd$long$region %>% 
  filter(year != 2020,
         year >= 2014,
         age_group != "014") %>% 
  mutate(age_group = factor(age_group, levels = c("04", "514", "15plus"),
                            ordered = TRUE)) %>% 
  group_by(g_whoregion, age_group, year) %>% 
  summarise(cases = sum(cases, na.rm = TRUE),
            .groups = "drop") %>% 
  select(location = g_whoregion, everything())

countries <- dd$long$country %>%
  filter(iso3 %in% const$high_burden) %>%
  filter(year >= 2014,
         year != 2020,
         age_group != "014") %>%
  mutate(age_group = factor(
    age_group,
    levels = c("04", "514", "15plus"),
    ordered = TRUE
  )) %>%
  group_by(iso3, age_group, year) %>%
  summarise(cases = sum(cases, na.rm = TRUE), 
            .groups = "drop") %>% 
  select(location = iso3, everything())

forecasts <- bind_rows(regions = regions, 
          countries = countries, 
          .id = "type") %>% 
  group_by(location, age_group, type) %>% 
## nest data by location & age group
  nest() %>% 
## create time-series
  mutate(ts = map(data,
                  function(series) {
                    select(series, -year) %>% 
                      ts(start = 2014, frequency = 1)
                  })) %>% 
  forecast_next_year(order = c(2, 0, 0),
                     drift = TRUE,
                     lambda = NULL)


```

```{r extract-missing-values}
# extract all time series with zero values
missing <- dd$long$country %>%
        filter(iso3 %in% const$high_burden) %>%
        filter(year >= 2014,
               year != 2020,
               age_group != "014") %>%
        mutate(age_group = factor(
                age_group,
                levels = c("04", "514", "15plus"),
                ordered = TRUE
        )) %>% 
        select(iso3, year, sex, age_group, cases) %>% 
        group_by(iso3, sex, age_group) %>% 
        nest() %>% 
        filter(map_lgl(data, function(d) {
                any(d$cases == 0 | is.na(d$cases))
        })) %>% 
        unnest(cols = c(data)) %>% 
        ungroup() %>% 
        mutate(cases = ifelse(cases == 0,
                              NA_integer_, 
                              cases))

saveRDS(missing,
        file = here::here("artefacts/missing.rds"))

```


```{r extract-predictions}

predictions <- forecasts %>% 
  mutate(prediction = map(forecast, function(series) {
    data.frame(
      point = series$mean,
      lower95 = series$lower[2],
      upper95 = series$upper[2]
    )
  })) %>% 
  select(type, location, age_group, prediction) %>% 
  unnest(cols = c(prediction))

saveRDS(predictions,
        file = here::here("artefacts/predictions.rds"))
```

# Problem

Some of the predictions are negative: 

```{r}
predictions %>% 
  filter(point <= 0 | lower95 <= 0)
```

